import { Vendor, ProductCategory, Product } from '@unified-commerce/types';

export const EXPANDED_CATEGORIES: ProductCategory[] = [
  {
    id: 'cat-cyberpunk',
    name: 'Cyberpunk Wearables',
    slug: 'cyberpunk-wearables',
    description: 'Neural augmentation, HUD visors, and bio-telemetry apparel engineered for urban cybernetics.',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    accentColor: '#00F2FE',
    subcategories: ['Neural Bands', 'HUD Visors', 'Smart Rings', 'Tactical Techwear'],
  },
  {
    id: 'cat-audio',
    name: 'Spatial Audio & Sound',
    slug: 'spatial-audio',
    description: 'Planar magnetic transducers, binaural monitors, and vacuum-tube analog converters.',
    icon: 'Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    accentColor: '#9B51E0',
    subcategories: ['Planar Headphones', 'Tube DACs', 'Studio Monitors', 'Spatial Earbuds'],
  },
  {
    id: 'cat-drones',
    name: 'Autonomous Flight & Drones',
    slug: 'autonomous-drones',
    description: 'AI obstacle-navigating quadcopters, long-range survey sensors, and gimbal stabilizers.',
    icon: 'Navigation',
    image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
    accentColor: '#FF007A',
    subcategories: ['Cinematic Quadcopters', 'LiDAR Scanners', 'FPV Racing', 'Autonomous Rovers'],
  },
  {
    id: 'cat-living',
    name: 'Minimalist Ambient Living',
    slug: 'minimalist-living',
    description: 'Circadian ambient lights, magnetic modular desks, and sculptured tactile workstations.',
    icon: 'Lamp',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    accentColor: '#FFB800',
    subcategories: ['Circadian Lamps', 'Ergonomic Seating', 'Desk Architecture', 'Basalt Diffusers'],
  },
  {
    id: 'cat-biometrics',
    name: 'Kinetic & Biometric Tech',
    slug: 'biometric-tech',
    description: 'EMS athletic recovery rigs, titanium sleep trackers, and kinetic energy chronographs.',
    icon: 'Activity',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    accentColor: '#00E5FF',
    subcategories: ['Smart Rings', 'EMS Suits', 'Kinetic Watches', 'Recovery Pods'],
  },
  {
    id: 'cat-keyboards',
    name: 'Mechanical & Hall-Effect Keyboards',
    slug: 'kinetic-keyboards',
    description: 'Precision CNC brass input devices, magnetic switches, and artisan tactile interfaces.',
    icon: 'Keyboard',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    accentColor: '#7928CA',
    subcategories: ['Hall Effect Boards', 'Custom Switches', 'Artisan Keycaps', 'Desk Armor'],
  },
  {
    id: 'cat-computing',
    name: 'Next-Gen Computing & Rigs',
    slug: 'next-gen-computing',
    description: 'Liquid-cooled mini workstations, neural accelerator pods, and carbon unibody laptops.',
    icon: 'Cpu',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
    accentColor: '#38EF7D',
    subcategories: ['Neural Pods', 'Liquid Modules', 'Carbon Laptops', 'Thunderbolt Docks'],
  },
  {
    id: 'cat-health',
    name: 'Smart Health & Continuous Diagnostics',
    slug: 'smart-health',
    description: 'Medical-grade continuous telemetry, sleep resonance spheres, and spectral scales.',
    icon: 'HeartPulse',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
    accentColor: '#FF416C',
    subcategories: ['Sleep Spheres', 'Continuous Glucose', 'Pulse Oximeters', 'Biometric Scales'],
  },
  {
    id: 'cat-apparel',
    name: 'Cybernetic Apparel & Techwear',
    slug: 'cybernetic-apparel',
    description: 'Graphene-lined weather shields, magnetic buckle slings, and heated exo-parkas.',
    icon: 'Shield',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80',
    accentColor: '#4FACFE',
    subcategories: ['Graphene Parkas', 'Magnetic Slings', 'Exo-Vests', 'All-Weather Boots'],
  },
  {
    id: 'cat-optics',
    name: 'AR / VR Spatial Optics',
    slug: 'spatial-optics',
    description: 'Micro-OLED spatial display glasses, eye-tracking prisms, and 6DoF haptic controllers.',
    icon: 'Glasses',
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=80',
    accentColor: '#F38181',
    subcategories: ['Micro-OLED Glasses', 'Haptic Gloves', 'Eye-Tracking Lenses', 'Spatial Trackers'],
  },
  {
    id: 'cat-mobility',
    name: 'Electric Micro-Mobility',
    slug: 'micro-mobility',
    description: 'Solid-state carbon electric skateboards, hub-motor e-bikes, and folding monowheels.',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    accentColor: '#FEE140',
    subcategories: ['Carbon Boards', 'Folding E-Bikes', 'Monowheels', 'Commuter Scooters'],
  },
  {
    id: 'cat-office',
    name: 'Ergonomic Workspace Architecture',
    slug: 'smart-office',
    description: 'Kinetic sit-stand desks, breathable carbon mesh seating, and magnetic rail organizers.',
    icon: 'Monitor',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    accentColor: '#00C9FF',
    subcategories: ['Kinetic Desks', 'Mesh Seating', 'Monitor Articulation', 'Cable Management'],
  },
  {
    id: 'cat-studio',
    name: 'Studio Holography & Optics',
    slug: 'studio-optics',
    description: 'Light-field holographic displays, 3D laser scanners, and cinema beam projectors.',
    icon: 'Eye',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    accentColor: '#FA709A',
    subcategories: ['Holographic Displays', '3D LiDAR Scanners', 'Laser Projectors', 'Key Lights'],
  },
  {
    id: 'cat-robotics',
    name: 'Robotics & Lab Automation',
    slug: 'robotics-automation',
    description: 'Programmable desktop robotic arms, bionic hand prosthetics, and telepresence units.',
    icon: 'Bot',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    accentColor: '#667EEA',
    subcategories: ['Robotic Arms', 'Telepresence Pods', 'AI Companions', 'Bionic Limbs'],
  },
  {
    id: 'cat-power',
    name: 'Solid-State Energy & Power',
    slug: 'power-energy',
    description: 'GaN ultra-fast charging docks, solid-state power bricks, and solar harvesting tiles.',
    icon: 'BatteryCharging',
    image: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
    accentColor: '#11998E',
    subcategories: ['GaN Chargers', 'Solid-State Banks', 'Solar Harvesting', 'Wireless Pads'],
  },
  {
    id: 'cat-chronographs',
    name: 'Luxury Kinetic Chronographs',
    slug: 'luxury-chronographs',
    description: 'Mechanical open-heart tourbillons, sapphire smartwatches, and kinetic micro-rotors.',
    icon: 'Watch',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    accentColor: '#E14F4F',
    subcategories: ['Tourbillon Automatics', 'Sapphire Smartwatches', 'Titanium Micro-Rotors', 'Dress Chronos'],
  },
];

export const EXPANDED_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Aether Labs',
    slug: 'aether-labs',
    tagline: 'Neural Interfaces & Cybernetic Wearables',
    description: 'Pioneering sensory augmentation devices, cybernetic apparel, and lightweight titanium neural bands designed in Tokyo.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewCount: 1420,
    totalProducts: 48,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Tokyo, Japan',
    badge: 'Top Seller',
    metrics: { gmv: 842000, completionRate: 99.4, avgDeliveryDays: 2.1 },
  },
  {
    id: 'vendor-2',
    name: 'SonicForge Acoustics',
    slug: 'sonicforge',
    tagline: 'Planar Magnetic Precision & Audiophile Engineering',
    description: 'Handcrafted planar-magnetic headphones and zero-noise vacuum tube DAC amplifiers machined from aerospace-grade aluminum.',
    logo: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    rating: 4.97,
    reviewCount: 980,
    totalProducts: 36,
    commissionRate: 0.075,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Stockholm, Sweden',
    badge: 'Top Seller',
    metrics: { gmv: 630000, completionRate: 99.8, avgDeliveryDays: 2.8 },
  },
  {
    id: 'vendor-3',
    name: 'Vortex Dynamics',
    slug: 'vortex-dynamics',
    tagline: 'Autonomous AI Drones & LiDAR Survey Systems',
    description: 'Ultra-lightweight obstacle-avoidance carbon fiber drones with cinematic gimbal stabilization and real-time mesh networking.',
    logo: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=1200&auto=format&fit=crop&q=80',
    rating: 4.89,
    reviewCount: 760,
    totalProducts: 32,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Zurich, Switzerland',
    badge: 'Verified Maker',
    metrics: { gmv: 920000, completionRate: 98.7, avgDeliveryDays: 3.2 },
  },
  {
    id: 'vendor-4',
    name: 'Komorebi Living',
    slug: 'komorebi-living',
    tagline: 'Smart Biophilic Home & Ambient Luminaires',
    description: 'Harmonious fusion of natural sustainable bamboo, matte basalt, and circadian smart lighting control algorithms.',
    logo: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.91,
    reviewCount: 1140,
    totalProducts: 44,
    commissionRate: 0.07,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Kyoto, Japan',
    badge: 'Eco Innovator',
    metrics: { gmv: 510000, completionRate: 99.1, avgDeliveryDays: 2.5 },
  },
  {
    id: 'vendor-5',
    name: 'Chronos Kinetic',
    slug: 'chronos-kinetic',
    tagline: 'Biomechanical Titanium Chronographs & Smart Rings',
    description: 'Surgical titanium smart rings with medical-grade photoplethysmography and mechanical open-heart balance wheels.',
    logo: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewCount: 650,
    totalProducts: 28,
    commissionRate: 0.085,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Geneva, Switzerland',
    badge: 'Top Seller',
    metrics: { gmv: 780000, completionRate: 99.6, avgDeliveryDays: 2.0 },
  },
  {
    id: 'vendor-6',
    name: 'OmniVision Spatial',
    slug: 'omnivision-spatial',
    tagline: 'Micro-OLED Spatial Glasses & Holographic Desktops',
    description: 'Featherlight 4K dual micro-OLED augmented reality displays engineered for 8-hour continuous spatial productivity.',
    logo: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=1200&auto=format&fit=crop&q=80',
    rating: 4.88,
    reviewCount: 890,
    totalProducts: 24,
    commissionRate: 0.09,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'San Francisco, USA',
    badge: 'Rising Star',
    metrics: { gmv: 610000, completionRate: 97.9, avgDeliveryDays: 2.3 },
  },
  {
    id: 'vendor-7',
    name: 'NeoPulse Athletics',
    slug: 'neopulse-athletics',
    tagline: 'EMS Activewear & Biometric Training Garments',
    description: 'Embedded electro-muscle stimulation dry-electrode compression wear synced with neural telemetry apps.',
    logo: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&auto=format&fit=crop&q=80',
    rating: 4.85,
    reviewCount: 520,
    totalProducts: 30,
    commissionRate: 0.07,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Austin, USA',
    badge: 'Verified Maker',
    metrics: { gmv: 340000, completionRate: 98.4, avgDeliveryDays: 2.4 },
  },
  {
    id: 'vendor-8',
    name: 'AeroCraft Lab',
    slug: 'aerocraft-lab',
    tagline: 'Hyper-Carbon Micro-Mobility & Mag-Lev Boards',
    description: 'Monocoque unibody electric surf and skate boards powered by solid-state lithium cells and silent hub motors.',
    logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=1200&auto=format&fit=crop&q=80',
    rating: 4.92,
    reviewCount: 410,
    totalProducts: 22,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Berlin, Germany',
    badge: 'Rising Star',
    metrics: { gmv: 420000, completionRate: 98.9, avgDeliveryDays: 3.5 },
  },
  {
    id: 'vendor-9',
    name: 'Quantum Soundworks',
    slug: 'quantum-soundworks',
    tagline: 'High-Res Vacuum Tube Amplifiers & Studio Monoliths',
    description: 'Analog purity merged with 32-bit 768kHz DSD decoding and toroidal copper power supplies.',
    logo: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 830,
    totalProducts: 26,
    commissionRate: 0.075,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'London, UK',
    badge: 'Top Seller',
    metrics: { gmv: 690000, completionRate: 99.5, avgDeliveryDays: 2.7 },
  },
  {
    id: 'vendor-10',
    name: 'Prism Hardware',
    slug: 'prism-hardware',
    tagline: 'Magnetic Desk Architecture & Kinetic Switches',
    description: 'Precision CNC-machined brass and polycarbonate input peripherals with hot-swappable hall-effect magnetic sensors.',
    logo: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.93,
    reviewCount: 1680,
    totalProducts: 50,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Seoul, South Korea',
    badge: 'Top Seller',
    metrics: { gmv: 910000, completionRate: 99.3, avgDeliveryDays: 2.2 },
  },
  // Vendors 11 to 35
  {
    id: 'vendor-11',
    name: 'Hyperion Energy Lab',
    slug: 'hyperion-energy',
    tagline: 'Solid-State GaN Charging Systems & Micro-Generators',
    description: 'Next-generation gallium nitride charging cubes and modular graphene emergency power banks.',
    logo: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&auto=format&fit=crop&q=80',
    rating: 4.91,
    reviewCount: 420,
    totalProducts: 24,
    commissionRate: 0.07,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Shenzhen, China',
    badge: 'Top Seller',
    metrics: { gmv: 560000, completionRate: 99.2, avgDeliveryDays: 2.3 },
  },
  {
    id: 'vendor-12',
    name: 'Monolith Workspaces',
    slug: 'monolith-workspaces',
    tagline: 'Minimalist Danish Desk Architecture & Ergonomics',
    description: 'Precision motorized dual-motor sit-stand desks made from reclaimed bog oak and bead-blasted steel.',
    logo: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.94,
    reviewCount: 310,
    totalProducts: 18,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Copenhagen, Denmark',
    badge: 'Eco Innovator',
    metrics: { gmv: 470000, completionRate: 98.9, avgDeliveryDays: 3.1 },
  },
  {
    id: 'vendor-13',
    name: 'CyberWeave Atelier',
    slug: 'cyberweave-atelier',
    tagline: 'Graphene Thermal Techwear & Modular Parkas',
    description: 'Weatherproof high-altitude parkas with integrated carbon nanotube heating grids and Fidlock buckles.',
    logo: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&auto=format&fit=crop&q=80',
    rating: 4.88,
    reviewCount: 510,
    totalProducts: 34,
    commissionRate: 0.075,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Milan, Italy',
    badge: 'Rising Star',
    metrics: { gmv: 620000, completionRate: 98.5, avgDeliveryDays: 2.6 },
  },
  {
    id: 'vendor-14',
    name: 'Spectral Lightfield',
    slug: 'spectral-lightfield',
    tagline: 'Glasses-Free 3D Holographic Display Pods',
    description: 'Multi-view spatial light-field displays designed for volumetric CAD rendering and real-time medical imaging.',
    logo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=1200&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewCount: 290,
    totalProducts: 16,
    commissionRate: 0.09,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Montreal, Canada',
    badge: 'Verified Maker',
    metrics: { gmv: 810000, completionRate: 99.4, avgDeliveryDays: 2.9 },
  },
  {
    id: 'vendor-15',
    name: 'BionicArm Dynamics',
    slug: 'bionicarm-dynamics',
    tagline: 'Programmable 6-Axis Desktop Robotics & Grippers',
    description: 'Repeatability under 0.02mm, harmonic drive gears, and open Python neural APIs for desktop automation.',
    logo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=1200&auto=format&fit=crop&q=80',
    rating: 4.92,
    reviewCount: 380,
    totalProducts: 20,
    commissionRate: 0.085,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Munich, Germany',
    badge: 'Top Seller',
    metrics: { gmv: 740000, completionRate: 99.0, avgDeliveryDays: 2.5 },
  },
  {
    id: 'vendor-16',
    name: 'NeuralLinker Biosystems',
    slug: 'neurallinker-biosystems',
    tagline: 'Continuous Dry-Contact EEG & Synaptic Monitors',
    description: 'Multi-electrode EEG headbands with onboard edge AI for real-time focus tracking and stress mitigation.',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop&q=80',
    rating: 4.93,
    reviewCount: 460,
    totalProducts: 25,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Tel Aviv, Israel',
    badge: 'Rising Star',
    metrics: { gmv: 590000, completionRate: 98.8, avgDeliveryDays: 2.2 },
  },
  {
    id: 'vendor-17',
    name: 'Zephyr Urban Flight',
    slug: 'zephyr-urban-flight',
    tagline: 'Quiet-Propeller Micro Drones & Thermal Sensors',
    description: 'Acoustically shielded carbon quadcopters for autonomous metropolitan package courier and thermal inspection.',
    logo: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=1200&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 340,
    totalProducts: 22,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Amsterdam, Netherlands',
    badge: 'Verified Maker',
    metrics: { gmv: 480000, completionRate: 98.6, avgDeliveryDays: 2.8 },
  },
  {
    id: 'vendor-18',
    name: 'Aegis Tactical Engineering',
    slug: 'aegis-tactical',
    tagline: 'Faraday EDC, Grade 5 Titanium Multi-Tools & Pouches',
    description: 'Emp-shielded signal-blocking tactical pouches, CNC milled titanium pry-bars, and sapphire optics.',
    logo: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 620,
    totalProducts: 38,
    commissionRate: 0.07,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Denver, USA',
    badge: 'Top Seller',
    metrics: { gmv: 710000, completionRate: 99.7, avgDeliveryDays: 1.9 },
  },
  {
    id: 'vendor-19',
    name: 'Apex Horology Geneva',
    slug: 'apex-horology',
    tagline: 'Hand-Finished Titanium Flying Tourbillons',
    description: 'Haute horlogerie combining micro-mechanical flying tourbillons with subtle biometric OLED notifications.',
    logo: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewCount: 210,
    totalProducts: 14,
    commissionRate: 0.09,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Geneva, Switzerland',
    badge: 'Top Seller',
    metrics: { gmv: 1250000, completionRate: 100, avgDeliveryDays: 2.0 },
  },
  {
    id: 'vendor-20',
    name: 'Titan Mech Peripherals',
    slug: 'titan-mech',
    tagline: 'Gasket-Mounted Titanium Keyboards & Hall Sensors',
    description: 'Solid billet titanium cases with Poron isolation dampening and rapid-trigger magnetic analog switches.',
    logo: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.94,
    reviewCount: 880,
    totalProducts: 42,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Taipei, Taiwan',
    badge: 'Top Seller',
    metrics: { gmv: 830000, completionRate: 99.2, avgDeliveryDays: 2.1 },
  },
  {
    id: 'vendor-21',
    name: 'Lumina Circadian Systems',
    slug: 'lumina-circadian',
    tagline: 'Melanopic Ratio Bio-Lighting & Solar Sync',
    description: 'Full-spectrum sunlight emulation lamps adjusting blue-light emissions according to your latitude.',
    logo: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.91,
    reviewCount: 390,
    totalProducts: 20,
    commissionRate: 0.075,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Helsinki, Finland',
    badge: 'Eco Innovator',
    metrics: { gmv: 390000, completionRate: 98.7, avgDeliveryDays: 3.0 },
  },
  {
    id: 'vendor-22',
    name: 'Kinetix Exosystems',
    slug: 'kinetix-exosystems',
    tagline: 'Carbon Fiber Active Knee & Spine Exosuits',
    description: 'Active motorized torque assist reducing joint fatigue by 40% during industrial and athletic activity.',
    logo: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&auto=format&fit=crop&q=80',
    rating: 4.87,
    reviewCount: 270,
    totalProducts: 16,
    commissionRate: 0.085,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Seoul, South Korea',
    badge: 'Rising Star',
    metrics: { gmv: 680000, completionRate: 98.1, avgDeliveryDays: 2.7 },
  },
  {
    id: 'vendor-23',
    name: 'Graphene Audio Labs',
    slug: 'graphene-audio',
    tagline: 'Nano-Graphene Diaphragm In-Ear Monitors',
    description: 'Distortion under 0.05% THD, 5Hz–65kHz frequency extension, and precision acoustic back-chambers.',
    logo: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewCount: 710,
    totalProducts: 30,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Oxford, UK',
    badge: 'Top Seller',
    metrics: { gmv: 790000, completionRate: 99.4, avgDeliveryDays: 2.4 },
  },
  {
    id: 'vendor-24',
    name: 'Strata Monocoque Works',
    slug: 'strata-monocoque',
    tagline: 'Toray T1000 Carbon Fiber e-Bikes & Frames',
    description: 'Sub-9kg carbon endurance electric road bikes with concealed 450Wh batteries and wireless shifting.',
    logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=1200&auto=format&fit=crop&q=80',
    rating: 4.93,
    reviewCount: 310,
    totalProducts: 18,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Torino, Italy',
    badge: 'Verified Maker',
    metrics: { gmv: 910000, completionRate: 98.9, avgDeliveryDays: 3.4 },
  },
  {
    id: 'vendor-25',
    name: 'HoloDeck Spatial Optics',
    slug: 'holodeck-spatial',
    tagline: '6DoF Micro-Projectors & Spatial Eyewear',
    description: 'Ultra-wide 110-degree FOV optical waveguide lenses projecting crisp 120Hz floating interface layers.',
    logo: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=1200&auto=format&fit=crop&q=80',
    rating: 4.89,
    reviewCount: 450,
    totalProducts: 22,
    commissionRate: 0.085,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'San Jose, USA',
    badge: 'Rising Star',
    metrics: { gmv: 670000, completionRate: 98.3, avgDeliveryDays: 2.2 },
  },
  {
    id: 'vendor-26',
    name: 'ZeroGravity Sleep Tech',
    slug: 'zerogravity-sleep',
    tagline: 'Active Resonance Mattresses & Biometric Pods',
    description: 'Dynamic pressure-relieving pneumatic chambers paired with sub-audible vibroacoustic delta-wave induction.',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 380,
    totalProducts: 19,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Reykjavik, Iceland',
    badge: 'Top Seller',
    metrics: { gmv: 850000, completionRate: 99.1, avgDeliveryDays: 3.3 },
  },
  {
    id: 'vendor-27',
    name: 'PulseWave Bio-Electronics',
    slug: 'pulsewave-bio',
    tagline: 'Targeted Neuro-Muscular Recovery Nodes',
    description: 'Wireless Bluetooth-synced EMS pads programmed for rapid lactic acid clearance and tendon healing.',
    logo: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&auto=format&fit=crop&q=80',
    rating: 4.88,
    reviewCount: 420,
    totalProducts: 26,
    commissionRate: 0.07,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Melbourne, Australia',
    badge: 'Verified Maker',
    metrics: { gmv: 430000, completionRate: 98.5, avgDeliveryDays: 2.9 },
  },
  {
    id: 'vendor-28',
    name: 'Solis Photovoltaic Labs',
    slug: 'solis-pv',
    tagline: 'Flexible Perovskite Solar Tiles & Power Skins',
    description: 'High-efficiency 28% solar conversion films designed to wrap portable gear, backpacks, and micro-shelters.',
    logo: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&auto=format&fit=crop&q=80',
    rating: 4.92,
    reviewCount: 310,
    totalProducts: 18,
    commissionRate: 0.075,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Freiburg, Germany',
    badge: 'Eco Innovator',
    metrics: { gmv: 410000, completionRate: 98.8, avgDeliveryDays: 2.6 },
  },
  {
    id: 'vendor-29',
    name: 'Obsidian Precision EDC',
    slug: 'obsidian-edc',
    tagline: 'Cryogenic MagnaCut Blades & Magnetic Clasps',
    description: '64 HRC vacuum heat-treated titanium folding knives and zero-play magnetic pocket tools.',
    logo: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&auto=format&fit=crop&q=80',
    rating: 4.97,
    reviewCount: 780,
    totalProducts: 36,
    commissionRate: 0.07,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Portland, USA',
    badge: 'Top Seller',
    metrics: { gmv: 690000, completionRate: 99.6, avgDeliveryDays: 2.0 },
  },
  {
    id: 'vendor-30',
    name: 'Elysian Valve Audio',
    slug: 'elysian-audio',
    tagline: 'Custom Single-Ended Triode Tube Amplifiers',
    description: 'Hand-wired 300B vacuum tube audio engines delivering harmonic lushness and uncompressed analog dynamics.',
    logo: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewCount: 490,
    totalProducts: 22,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Kyoto, Japan',
    badge: 'Top Seller',
    metrics: { gmv: 980000, completionRate: 99.9, avgDeliveryDays: 2.8 },
  },
  {
    id: 'vendor-31',
    name: 'NeuroSync Neural Labs',
    slug: 'neurosync-labs',
    tagline: 'Synaptic Sleep & Focus Modulation Bands',
    description: 'Transcranial electrical stimulation headgear enhancing deep sleep slow-wave oscillation.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop&q=80',
    rating: 4.93,
    reviewCount: 390,
    totalProducts: 24,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Singapore',
    badge: 'Rising Star',
    metrics: { gmv: 520000, completionRate: 98.9, avgDeliveryDays: 2.1 },
  },
  {
    id: 'vendor-32',
    name: 'CarbonCopter Drone Labs',
    slug: 'carboncopter-labs',
    tagline: 'Autonomous LiDAR Search & Rescue Drones',
    description: 'IP67 storm-ready heavy-lift carbon hexacopters with thermal night vision and satellite relays.',
    logo: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=1200&auto=format&fit=crop&q=80',
    rating: 4.91,
    reviewCount: 260,
    totalProducts: 18,
    commissionRate: 0.085,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Zurich, Switzerland',
    badge: 'Verified Maker',
    metrics: { gmv: 770000, completionRate: 99.2, avgDeliveryDays: 3.1 },
  },
  {
    id: 'vendor-33',
    name: 'ForgePoint Titanium Works',
    slug: 'forgepoint-titanium',
    tagline: 'Additive Manufacturing & Topological Peripherals',
    description: 'Electron beam melted (EBM) titanium mouse skeletons, mechanical keycaps, and articulating monitor arms.',
    logo: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 540,
    totalProducts: 32,
    commissionRate: 0.075,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Osaka, Japan',
    badge: 'Top Seller',
    metrics: { gmv: 640000, completionRate: 99.5, avgDeliveryDays: 2.3 },
  },
  {
    id: 'vendor-34',
    name: 'PureBasalt Acoustics',
    slug: 'purebasalt-acoustics',
    tagline: 'Volcanic Basalt Enclosure Studio Monitors',
    description: 'Resonance-free volcanic stone acoustic cabinets with diamond-coated beryllium dome tweeters.',
    logo: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    rating: 4.97,
    reviewCount: 310,
    totalProducts: 16,
    commissionRate: 0.08,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Oslo, Norway',
    badge: 'Top Seller',
    metrics: { gmv: 880000, completionRate: 99.8, avgDeliveryDays: 2.7 },
  },
  {
    id: 'vendor-35',
    name: 'LiquidLogic Compute',
    slug: 'liquidlogic-compute',
    tagline: 'Sub-Ambient Fluorinert Immersion Rigs',
    description: 'Whisper-quiet direct-die cooling modules and miniature desktop GPU cluster cubes.',
    logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=200&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.94,
    reviewCount: 420,
    totalProducts: 20,
    commissionRate: 0.085,
    isVerified: true,
    kycStatus: 'VERIFIED',
    location: 'Austin, USA',
    badge: 'Rising Star',
    metrics: { gmv: 710000, completionRate: 98.9, avgDeliveryDays: 2.4 },
  },
];

/* ─────────────────────────────────────────────────────────────
   Deterministic 1,024+ Product Generator Engine
───────────────────────────────────────────────────────────── */

const CATEGORY_VOCABULARIES: Record<
  string,
  {
    prefixes: string[];
    nouns: string[];
    models: string[];
    adjectives: string[];
    images: string[];
    vendorIds: string[];
    basePriceMin: number;
    basePriceMax: number;
    tagsPool: string[];
    specsTemplates: Record<string, string[]>;
  }
> = {
  'cyberpunk-wearables': {
    prefixes: ['Aether', 'Omni', 'Synapse', 'Cortex', 'Neuro', 'Quantum', 'Apex', 'Titan', 'Spectra', 'Cipher'],
    nouns: ['Neural Band', 'HUD Visor', 'Synaptic Ring', 'Exo-Glove', 'Biometric Crown', 'Pulse Link', 'Ocular Lens'],
    models: ['MK-I', 'MK-II', 'Pro', 'X1', 'X9 Ultra', 'Prime', 'Zero', 'Apex Carbon', 'Matrix Edition'],
    adjectives: ['Machined from Grade 5 titanium', 'Equipped with sub-millisecond EEG sensors', 'Embedded with quantum haptics'],
    images: [
      'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-1', 'vendor-5', 'vendor-6', 'vendor-16', 'vendor-31'],
    basePriceMin: 249,
    basePriceMax: 1899,
    tagsPool: ['EEG', 'Cyberpunk', 'Titanium', 'Bionic', 'Haptics', 'Neural', 'Bio-Telemetry', 'OLED'],
    specsTemplates: {
      'Sensor Type': ['8-Channel EEG Matrix', 'Photoplethysmography Array', 'Dual Dry-Electrode Array', 'Neural Mesh v3'],
      'Battery Life': ['36 Hours Continuous', '48 Hours Standby', '72 Hours Eco Mode', '5 Days Low-Power Sync'],
      'Material': ['Grade 5 Aerospace Titanium', 'Graphene Weave & Ceramic', 'Carbon Monocoque & Sapphire Glass'],
      'Latency': ['< 0.8ms Direct BLE', '< 1.2ms Sub-GHz Relay', '< 0.5ms Ultra-Wideband'],
    },
  },
  'spatial-audio': {
    prefixes: ['SonicForge', 'Elysium', 'Acoustic', 'Verve', 'Planar', 'Quantum', 'Harmonic', 'Zero', 'Binaural', 'Resonance'],
    nouns: ['Planar Headphones', 'Tube DAC Amp', 'Studio Monitor', 'Spatial Earbuds', 'Toroidal Transformer', 'Acoustic Monolith'],
    models: ['Reference 1', 'Master Edition', 'Studio Pro', 'Signature 9', 'DSD-1024', 'Diamond Beryllium', 'Aero Black'],
    adjectives: ['Handcrafted with planar magnetic foil', 'Featuring zero-negative-feedback triode tubes', 'Calibrated for 32-bit mastering'],
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-2', 'vendor-9', 'vendor-23', 'vendor-30', 'vendor-34'],
    basePriceMin: 189,
    basePriceMax: 2999,
    tagsPool: ['Audiophile', 'Planar', 'Hi-Res Audio', 'Vacuum Tube', 'Balanced 4.4mm', 'Spatial Audio', 'DSD'],
    specsTemplates: {
      'Frequency Response': ['5Hz – 55kHz (+/- 0.5dB)', '10Hz – 48kHz', '4Hz – 65kHz Studio Reference'],
      'Impedance': ['32 Ohms High Sensitivity', '300 Ohms Studio Standard', '64 Ohms Planar Driver'],
      'Total Harmonic Distortion': ['< 0.005% at 1kHz', '< 0.01% Pure Analog', '< 0.002% Ultra-Clean'],
      'Chassis': ['Milled 6061 Aluminum & Walnut', 'Solid Volcanic Basalt Stone', 'CNC Titanium & Lambskin'],
    },
  },
  'autonomous-drones': {
    prefixes: ['Vortex', 'Aero', 'Zephyr', 'Apex', 'Falcon', 'Specter', 'Nimbus', 'Carbon', 'Thermal', 'Stratosphere'],
    nouns: ['Cinema Drone', 'LiDAR Quadcopter', 'FPV Interceptor', 'Survey Hexacopter', 'Micro-Scout', 'Telemetry Rover'],
    models: ['Pro 8K', 'V4 Carbon', 'LiDAR Matrix', 'Suborbital Edition', 'Thermal Core', 'Storm-Proof IP67', 'Long-Range 15km'],
    adjectives: ['Built with omnidirectional collision avoidance', 'Equipped with 3-axis mechanical gimbal', 'Powered by edge neural vision'],
    images: [
      'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-3', 'vendor-17', 'vendor-32'],
    basePriceMin: 399,
    basePriceMax: 4200,
    tagsPool: ['Drone', 'Autonomous', 'LiDAR', '8K Video', 'Carbon Fiber', 'Long Range', 'Thermal', 'Obstacle Avoidance'],
    specsTemplates: {
      'Flight Duration': ['42 Minutes Hover Time', '55 Minutes Eco-Cruise', '35 Minutes High-Speed 90km/h'],
      'Camera Sensor': ['1-inch CMOS 8K 60fps', 'Dual Optical 4K + FLIR Thermal', '4/3 Hasselblad Color Matrix'],
      'Transmission Range': ['15 km OcuSync 4.0 Pro', '12 km Encrypted Mesh Protocol', '20 km Satellite Augmented'],
      'Weight & Frame': ['680g Toray Carbon Fiber Unibody', '890g Titanium Folding Airframe', '420g Ultralight FPV'],
    },
  },
  'minimalist-living': {
    prefixes: ['Komorebi', 'Monolith', 'Basalt', 'Zen', 'Aura', 'Circadian', 'Solace', 'Pure', 'Lumina', 'Harmonic'],
    nouns: ['Circadian Lamp', 'Magnetic Levitation Planter', 'Basalt Diffuser', 'Acoustic Panel', 'Ambient Prism', 'Touch Table'],
    models: ['Bamboo Edition', 'Basalt Black', 'OLED Solar', 'Minimal 01', 'Atmosphere Pro', 'Studio Edition'],
    adjectives: ['Crafted from sustainable Kyoto bamboo', 'Synchronized to biological circadian rhythms', 'Featuring tactile magnetic switches'],
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-4', 'vendor-12', 'vendor-21'],
    basePriceMin: 89,
    basePriceMax: 1450,
    tagsPool: ['Minimalist', 'Circadian', 'Smart Home', 'Bamboo', 'Basalt', 'Biophilic', 'Ambient Light'],
    specsTemplates: {
      'Color Temperature': ['1800K (Candlelight) – 6500K (Noon Sun)', 'Full Spectrum 98+ CRI Solar Emulation'],
      'Materials': ['Sustainable Smoked Bamboo & Cast Basalt', 'Milled Ash Wood & Matte Aluminum'],
      'Smart Connectivity': ['Matter & Thread Certified', 'Apple HomeKit, Zigbee 3.0, BLE 5.3'],
      'Power Consumption': ['18W High-Efficiency LED Array', '24W Magnetic Induction Base'],
    },
  },
  'biometric-tech': {
    prefixes: ['Chronos', 'NeoPulse', 'PulseWave', 'BioSync', 'Vigor', 'Kinetic', 'Titan', 'Oura', 'Helix', 'Quantum'],
    nouns: ['Smart Ring', 'EMS Recovery Suit', 'Biometric Band', 'Kinetic Tracker', 'Recovery Sleeve', 'Sleep Sphere'],
    models: ['Titanium Stealth', 'Ceramic Gen 4', 'Pro Athlete', 'Core Alpha', 'Medical Sync', 'Carbon Ultra'],
    adjectives: ['Milled from biocompatible Grade 5 titanium', 'Equipped with medical clinical-grade PPG sensors', 'Calibrated for real-time recovery metrics'],
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-5', 'vendor-7', 'vendor-22', 'vendor-27'],
    basePriceMin: 149,
    basePriceMax: 1699,
    tagsPool: ['Biometrics', 'Smart Ring', 'Sleep Tracking', 'Heart Rate', 'Titanium', 'EMS', 'Fitness'],
    specsTemplates: {
      'Water Resistance': ['100m / 10 ATM Diving Rating', '50m / 5 ATM Swimproof'],
      'Biometric Sensors': ['Red + Infrared SpO2 + Green Heart Rate + Skin Temperature', 'Dual Dry EMS Conductive Channels'],
      'Battery & Charging': ['7 Days Continuous Telemetry / 45 Min Magnetic Fast Charge', '10 Days Low-Power Sync'],
      'Biocompatibility': ['Nickel-Free Medical Grade Titanium & Hypoallergenic Resin', 'Antibacterial Silver-Ion Weave'],
    },
  },
  'kinetic-keyboards': {
    prefixes: ['Prism', 'Titan', 'ForgePoint', 'Apex', 'Matrix', 'Vortex', 'Kinetix', 'Cipher', 'Monolith', 'Quantum'],
    nouns: ['Hall Effect Keyboard 75%', 'CNC Brass Keyboard 65%', 'Magnetic Switch Module', 'Titanium Artisan Cap', 'Desk Armor Pad'],
    models: ['Rapid Trigger Pro', 'Billet Edition', 'Magnetic Core', 'Gasket Mount', 'Anodized Stealth', 'Cerakote White'],
    adjectives: ['Featuring 0.05mm customizable rapid trigger actuation', 'Machined from solid brass and 6063 aluminum', 'Equipped with hot-swappable hall sensors'],
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-10', 'vendor-20', 'vendor-33'],
    basePriceMin: 129,
    basePriceMax: 789,
    tagsPool: ['Mechanical Keyboard', 'Hall Effect', 'Rapid Trigger', 'CNC Aluminum', 'Custom Peripherals', 'Titanium'],
    specsTemplates: {
      'Actuation Point': ['0.1mm to 4.0mm Dynamic Range (0.05mm precision)', '1.5mm Linear Pre-Travel'],
      'Polling Rate': ['8000Hz (0.125ms latency)', '4000Hz Ultra-Fast Tri-Mode Wireless'],
      'Structure': ['Poron Gasket Mount with Silicone Sound Dampening Pad', 'Top-Mounted Brass Plate with Flex Cuts'],
      'Weight': ['2.2 kg Solid Desk Presence', '1.8 kg Heavy Anodized Aluminum'],
    },
  },
  'next-gen-computing': {
    prefixes: ['LiquidLogic', 'Carbon', 'Neural', 'Hyper', 'Quantum', 'Apex', 'Core', 'Vortex', 'Matrix', 'Pro'],
    nouns: ['Neural Accelerator Pod', 'Liquid-Cooled Compute Cube', 'Carbon Mini-Workstation', 'Thunderbolt eGPU Hub', 'AI Coprocessor Dock'],
    models: ['RTX 5090 Ready', 'M4 Ultra Spec', 'Dual Fluorinert Loop', '128GB Unified Memory', '400W GaN Internal'],
    adjectives: ['Cooled with silent sub-ambient liquid fluorinert', 'Delivering 400 TOPS of localized on-device AI inference', 'Machined from monocoque carbon fiber'],
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-35', 'vendor-15', 'vendor-11'],
    basePriceMin: 599,
    basePriceMax: 4899,
    tagsPool: ['Compute', 'Workstation', 'AI Accelerator', 'Liquid Cooled', 'Thunderbolt 5', 'GPU', 'Carbon'],
    specsTemplates: {
      'Compute Density': ['640 TOPS INT8 Edge Neural Throughput', '1.2 PFLOPS Half-Precision AI Matrix'],
      'Thermal Performance': ['< 18dB Silent Fluorinert Direct-Die Immersion', 'Triple Copper Radiators with Noctua Fans'],
      'Connectivity': ['Dual Thunderbolt 5 (80Gbps) + 10GbE SFP+ Optical Port', 'PCIe Gen 5 NVMe 14,000MB/s Read'],
      'Power Unit': ['Built-in 850W Platinum GaN Titanium Power Supply', '650W Silent Passive GaN Power Brick'],
    },
  },
  'smart-health': {
    prefixes: ['ZeroGravity', 'PulseWave', 'BioSync', 'Healix', 'Spectral', 'Neuro', 'Clinical', 'Omni', 'Vital', 'LifeLink'],
    nouns: ['Sleep Resonance Sphere', 'Continuous Glucose Patch', 'Spectral Health Scale', 'Pulse Oximeter Matrix', 'Circadian Mask'],
    models: ['Clinical Grade', 'V3 Delta', 'Biosensing Pro', 'Home Lab Edition', 'Multi-Frequency', 'Wireless FastSync'],
    adjectives: ['FDA Registered & CE Class IIa Medical Certified', 'Monitors deep slow-wave delta sleep phases', 'Non-invasive infrared continuous telemetry'],
    images: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-26', 'vendor-7', 'vendor-16'],
    basePriceMin: 89,
    basePriceMax: 1299,
    tagsPool: ['Smart Health', 'Medical Grade', 'Sleep Tracker', 'Biometrics', 'Glucose Monitor', 'Health Tech'],
    specsTemplates: {
      'Measurement Metric': ['Heart Rate Variability (HRV) + ECG + SpO2 + Core Temp', 'Sub-Dermal Interstitial Glucose Sensor'],
      'Precision Accuracy': ['+/- 1 bpm clinical reference match (Holter validated)', '99.4% correlation with laboratory gold standard'],
      'Data Privacy': ['End-to-End AES-256 Encrypted on Device / Zero Cloud Sell', 'HIPAA & GDPR Article 20 Compliant Export'],
      'Battery / Wear': ['14-Day Continuous Sensor Patch', '30-Day Rechargeable Li-Ion Cell'],
    },
  },
  'cybernetic-apparel': {
    prefixes: ['CyberWeave', 'Aegis', 'Kinetix', 'NeoPulse', 'Graphene', 'Urban', 'Apex', 'Monolith', 'Carbon', 'Tactical'],
    nouns: ['Graphene Thermal Parka', 'Magnetic Buckle Sling', 'Kevlar Reinforced Exo-Vest', 'All-Weather Tech Pants', 'Modular Bag'],
    models: ['Stealth Black', 'Cryo Weather', 'Fidlock Carbon', 'Storm Shield 20K', 'Sub-Zero Edition', 'Urban Commuter'],
    adjectives: ['Infused with flexible carbon nanotube heating grids', 'Waterproof 28,000mm hydrostatic head rating', 'Equipped with rapid magnetic Fidlock hardware'],
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-13', 'vendor-18', 'vendor-7'],
    basePriceMin: 120,
    basePriceMax: 1850,
    tagsPool: ['Techwear', 'Graphene', 'Weatherproof', 'Fidlock', 'Modular', 'Tactical', 'Carbon'],
    specsTemplates: {
      'Waterproof / Breathable': ['28,000mm Hydrostatic Head / 20,000g/m2 Breathability', '30,000mm 3-Layer GORE-TEX Pro Equivalent'],
      'Heating Architecture': ['3-Zone Carbon Nanotube Grid (Low 38C / Med 45C / High 55C)', 'Passive Graphene Heat Redistribution Layer'],
      'Hardware': ['German Fidlock V-Buckles & YKK Aquaguard Zippers', 'Surgical Titanium Zipper Pulls & Duraflex Clips'],
      'Capacity & Weight': ['18L Expandable to 26L / 820g Cordura 500D Nylon', '1.1 kg Insulated Winter Shell'],
    },
  },
  'spatial-optics': {
    prefixes: ['OmniVision', 'Spectral', 'HoloDeck', 'Prism', 'Apex', 'Spatial', 'Meta', 'Virtual', 'Ocular', 'Optic'],
    nouns: ['Micro-OLED Spatial Glasses', 'Haptic Force Glove', 'Eye-Tracking Waveguide', 'Volumetric Spatial Tracker', 'Light Field Visor'],
    models: ['Dual 4K Pro', 'Ultra FOV 110', 'Waveguide Prime', 'Developer Kit 3', 'Featherlight 72g', 'Spatial Spatial Gen2'],
    adjectives: ['Featuring dual Sony 4K micro-OLED micro-displays', 'Weighing only 72g for all-day comfort', 'Equipped with sub-millimeter 6DoF optical tracking'],
    images: [
      'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-6', 'vendor-14', 'vendor-25'],
    basePriceMin: 499,
    basePriceMax: 3499,
    tagsPool: ['AR', 'VR', 'Spatial Optics', 'Micro-OLED', '4K', 'Eye Tracking', 'Haptics'],
    specsTemplates: {
      'Display Panel': ['Dual 0.71-inch 4K Micro-OLED (3840x2160 per eye)', 'Custom Holographic Waveguide 120Hz 1800 nits'],
      'Field of View': ['105 Degrees Diagonal Spatial Immersion', '110 Degrees Ultra-Wide Panoramic FOV'],
      'Tracking & Sensors': ['6DoF Inside-Out Dual Fisheye + Dual IR Eye Tracking', 'Spatial Acoustic Beamforming Array with 4 Microphones'],
      'Weight': ['74 grams Featherweight Titanium Frame', '88 grams Carbon Magnesium Architecture'],
    },
  },
  'micro-mobility': {
    prefixes: ['AeroCraft', 'Strata', 'Zephyr', 'Turbo', 'Veloce', 'Monolith', 'Apex', 'Hyper', 'Stealth', 'Volt'],
    nouns: ['Carbon Electric Skateboard', 'Folding e-Bike', 'Hub-Drive Monowheel', 'Titanium Commuter Scooter', 'Mag-Lev Hydrofoil'],
    models: ['Toray T1000', 'Dual 3000W Motors', 'Long-Range 60km', 'Air Transit Fold', 'Carbon Monocoque', 'All-Terrain AT'],
    adjectives: ['Built with Toray T1000 carbon unibody deck', 'Top speed of 55 km/h with regenerative braking', 'Featuring swappable solid-state lithium packs'],
    images: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-8', 'vendor-24', 'vendor-17'],
    basePriceMin: 449,
    basePriceMax: 3899,
    tagsPool: ['Electric Vehicle', 'e-Skateboard', 'e-Bike', 'Carbon Fiber', 'Commuter', 'Micro-Mobility'],
    specsTemplates: {
      'Top Speed & Range': ['52 km/h Top Speed / 65 km Real-World Range', '45 km/h Top Speed / 80 km Range'],
      'Motor Architecture': ['Dual 2500W Belt Drive Brushless Motors', 'Direct-Drive 1500W In-Wheel Hub Motors'],
      'Battery System': ['648Wh Samsung 21700 Molicel Pack with Smart BMS', '820Wh Removable Fast-Swap Pack'],
      'Weight & Deck': ['8.4 kg Monocoque Carbon Deck with Drop-Down Concave', '12.8 kg Lightweight Folding Frame'],
    },
  },
  'smart-office': {
    prefixes: ['Monolith', 'Komorebi', 'Lumina', 'Ergo', 'Apex', 'Titan', 'Prism', 'Studio', 'Aero', 'Harmonic'],
    nouns: ['Kinetic Sit-Stand Desk', 'Carbon Mesh Ergonomic Chair', 'Gas-Spring Monitor Arm', 'Magnetic Cable Rail', 'Basalt Desk Pad'],
    models: ['Dual Motor Solid Oak', '4-Memory Preset', 'Dynamic Lumbar', 'Heavy Duty 49-inch', 'Titanium Black', 'Minimal White'],
    adjectives: ['Motorized anti-collision dual silent motors', 'Engineered with responsive self-adjusting lumbar mesh', 'Rated for heavy 49-inch ultrawide screens'],
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-12', 'vendor-4', 'vendor-20'],
    basePriceMin: 89,
    basePriceMax: 2199,
    tagsPool: ['Ergonomics', 'Standing Desk', 'Workspace', 'Office Chair', 'Monitor Arm', 'Minimalist'],
    specsTemplates: {
      'Height Range': ['62cm – 128cm Dual Stage Telescopic Legs', 'Dynamic 4D Armrest & 135 Degree Recline'],
      'Load Capacity': ['160 kg Heavy Payload Capacity', 'Holds Up to 22 kg Displays (32"-57" Ultrawide)'],
      'Motor Speed / Noise': ['40mm/s Elevation Speed / < 38dB Whisper Silent Motor', 'Smooth Gas-Spring Counterbalance'],
      'Materials': ['Solid European White Oak & Recycled Steel Columns', 'Breathable Aerospace Elastomer Mesh'],
    },
  },
  'studio-optics': {
    prefixes: ['Spectral', 'OmniVision', 'HoloDeck', 'Optic', 'Studio', 'Cinema', 'Quantum', 'Laser', 'Volumetric', 'Photon'],
    nouns: ['Holographic 3D Display', '3D Handheld LiDAR Scanner', 'Laser Beam Cinema Projector', 'RGBWW Studio Key Light', 'Turntable Scanner'],
    models: ['4K Volumetric', '0.01mm Precision', '4500 ANSI Lumens', 'CRI 99 Studio', 'Light-Field Gen3', 'Portable Pro'],
    adjectives: ['Captures 1,000,000 points per second in full color', 'Displays 45 viewing angles with zero glasses required', 'Outputs pure RGB laser with BT.2020 color gamut'],
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-14', 'vendor-25', 'vendor-6'],
    basePriceMin: 299,
    basePriceMax: 4400,
    tagsPool: ['Hologram', '3D Scanner', 'LiDAR', 'Studio Lighting', 'Projector', 'Light Field', 'Cinema'],
    specsTemplates: {
      'Scanning / Display Res': ['0.02mm Single-Frame Scan Accuracy / 30 fps Capture', '3840x2160 45-View Spatial Light-Field Matrix'],
      'Color Gamut': ['110% Rec.2020 Pure Triple Laser Gamut', 'CRI 98+ / TLCI 99 Studio Broadcast Standard'],
      'Light Output': ['3,800 ANSI Lumens ALPD 4.0 Laser', '200W Bowens Mount High-Output Key'],
      'Weight & Interface': ['1.2 kg Magnesium Unibody / USB-C Thunderbolt 4', 'HDMI 2.1 eARC + DisplayPort 1.4 Spatial Sync'],
    },
  },
  'robotics-automation': {
    prefixes: ['BionicArm', 'Cyber', 'Apex', 'Matrix', 'Nexus', 'Kinetic', 'Bot', 'Automation', 'Titan', 'Synapse'],
    nouns: ['Desktop 6-Axis Robotic Arm', 'Bionic Prosthetic Gripper', 'AI Companion Mobile Unit', 'Telepresence Pod', 'Automated Lab Sorter'],
    models: ['Harmonic Drive 0.02mm', 'Python API Pro', 'Edge Vision 4K', 'Carbon Joint v2', 'Industrial Precision', 'Silent Core'],
    adjectives: ['Sub-0.02mm repeatable precision with harmonic drive gears', 'Open Python SDK with PyTorch kinematic solver support', 'Equipped with tactile force-sensing silicone fingertips'],
    images: [
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-15', 'vendor-3', 'vendor-35'],
    basePriceMin: 699,
    basePriceMax: 4600,
    tagsPool: ['Robotics', 'Robotic Arm', 'Automation', 'Bionic', 'AI Companion', 'Python API', 'Harmonic Drive'],
    specsTemplates: {
      'Payload & Reach': ['1.5 kg Payload / 620mm Maximum Reach Radius', '2.5 kg Industrial Payload / 850mm Spherical Envelope'],
      'Repeatability': ['+/- 0.02mm Sub-Millimeter Harmonic Gear Precision', '+/- 0.05mm Closed-Loop Optical Encoder'],
      'Degrees of Freedom': ['6 Axis Full Rotation with Integrated Pneumatic Air Line', '5-Finger Multi-Grip Adaptive Prosthetic Hand'],
      'API & Controls': ['Python, ROS 2, C++, MATLAB Native API over Gigabit Ethernet', 'Edge TensorRT Vision Pipeline 60fps'],
    },
  },
  'power-energy': {
    prefixes: ['Hyperion', 'Solis', 'Quantum', 'Volt', 'Power', 'GaN', 'Apex', 'Core', 'SolidState', 'Graphene'],
    nouns: ['GaN 240W Quantum Charging Cube', 'Solid-State 100Wh Power Bank', 'Flexible Solar Folding Tile', 'Magnetic Wireless Charging Base', 'Hydrogen Fuel Pod'],
    models: ['240W 4-Port GaN', 'Titanium 27000mAh', 'Solar 100W IP68', 'Qi2 MagSafe 15W', 'Cyber Power Prime', 'Ultra Slim 65W'],
    adjectives: ['Powered by GaNFast 5th-gen gallium nitride semiconductors', 'Charges MacBook Pro, iPad, and iPhone simultaneously at peak velocity', 'Features OLED power output telemetry display'],
    images: [
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-11', 'vendor-28', 'vendor-20'],
    basePriceMin: 39,
    basePriceMax: 899,
    tagsPool: ['GaN Charger', 'Power Bank', 'Solar Energy', 'Fast Charging', 'Solid State', 'USB-C PD 3.1'],
    specsTemplates: {
      'Output Power': ['240W Total Output (Single Port 140W USB-PD 3.1)', '165W Dual Simultaneous USB-C Fast Charge'],
      'Capacity & Cells': ['27,650mAh (99.6Wh Flight Approved) Solid-State Cells', '20,000mAh Semi-Solid Electrolyte Safe Pack'],
      'Display Telemetry': ['IPS Real-Time Wattage / Voltage / Temperature Monitor', 'Color OLED Dynamic Power Distribution Matrix'],
      'Thermal Protection': ['Active Graphene Heat Dissipation with 100x/sec Thermal Scans', 'Aerospace Fireproof Polycarbonate Shell'],
    },
  },
  'luxury-chronographs': {
    prefixes: ['Chronos', 'Apex Horology', 'Obsidian', 'Geneva', 'Tourbillon', 'Titan', 'Verve', 'Kinetic', 'Sapphire', 'Zenith'],
    nouns: ['Flying Tourbillon Chronograph', 'Open-Heart Automatic Watch', 'Titanium Micro-Rotor Watch', 'Sapphire Crystal Smartwatch', 'Grand Complication Chrono'],
    models: ['Grade 5 Titanium', 'Forged Carbon Bezel', 'Skeleton Dial 72h', 'Sapphire Unibody', 'Tourbillon 1/100s', 'Heritage Geneva'],
    adjectives: ['Hand-assembled in Geneva with Côtes de Genève finishing', 'Features an exposed flying tourbillon cage rotating every 60 seconds', 'Carved from monolithic synthetic sapphire block'],
    images: [
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    ],
    vendorIds: ['vendor-19', 'vendor-5', 'vendor-29'],
    basePriceMin: 599,
    basePriceMax: 4899,
    tagsPool: ['Luxury Watch', 'Tourbillon', 'Titanium', 'Sapphire Crystal', 'Automatic', 'Chronograph', 'Horology'],
    specsTemplates: {
      'Movement Caliber': ['Caliber CH-9002 Flying Tourbillon (28,800 vph / 4Hz)', 'In-House Micro-Rotor Automatic (72-Hour Power Reserve)'],
      'Case & Crystal': ['Grade 5 Titanium (41mm) with Double Anti-Reflective Sapphire', 'Solid Monolithic Sapphire Crystal Case with Titanium Screws'],
      'Water Resistance': ['100m / 10 ATM with Screw-Down Crown', '50m / 5 ATM Exhibition Case Back'],
      'Strap & Clasp': ['FKM Fluorocarbon Rubber with Titanium Deployant Clasp', 'Hand-Stitched Italian Horween Leather with Titanium Pin Buckle'],
    },
  },
};

/**
 * Generate 1,024 rich, realistic marketplace products
 */
export function generateLargeScaleCatalog(existingFlagshipProducts: Product[] = []): Product[] {
  const result: Product[] = [...existingFlagshipProducts];
  const existingIds = new Set(existingFlagshipProducts.map((p) => p.id));
  const existingSlugs = new Set(existingFlagshipProducts.map((p) => p.slug));

  let nextIdNum = existingFlagshipProducts.length + 1;
  const targetTotal = 1024;
  const categoriesCount = EXPANDED_CATEGORIES.length;
  const neededExtra = Math.max(0, targetTotal - result.length);

  // Distribute needed items evenly across categories
  for (let i = 0; i < neededExtra; i++) {
    const cat = EXPANDED_CATEGORIES[i % categoriesCount];
    const vocab = CATEGORY_VOCABULARIES[cat.slug] || CATEGORY_VOCABULARIES['cyberpunk-wearables'];

    const prefix = vocab.prefixes[(i * 3 + 1) % vocab.prefixes.length];
    const noun = vocab.nouns[(i * 5 + 2) % vocab.nouns.length];
    const model = vocab.models[(i * 7 + 3) % vocab.models.length];

    const productName = `${prefix} ${noun} ${model}`;
    let slug = productName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)+/g, '');

    // Ensure unique slug
    if (existingSlugs.has(slug)) {
      slug = `${slug}-${nextIdNum}`;
    }
    existingSlugs.add(slug);

    const vendorId = vocab.vendorIds[i % vocab.vendorIds.length];
    const vendor = EXPANDED_VENDORS.find((v) => v.id === vendorId) || EXPANDED_VENDORS[0];

    const subcategory = cat.subcategories
      ? cat.subcategories[i % cat.subcategories.length]
      : cat.name;

    // Realistic price calculation
    const priceSpan = vocab.basePriceMax - vocab.basePriceMin;
    const priceRatio = ((i * 37 + 13) % 100) / 100;
    const price = Math.round(vocab.basePriceMin + priceSpan * priceRatio);

    // Realistic discount: ~35% of products have originalPrice (10% to 35% discount)
    const hasDiscount = (i % 3 === 0);
    const discountFactor = 1.1 + ((i % 25) / 100);
    const originalPrice = hasDiscount ? Math.round(price * discountFactor) : undefined;

    // Realistic stock: ~5% out of stock (0), ~10% low stock (< 10), ~85% in stock (25 - 450)
    let stock = 0;
    if (i % 20 === 0) {
      stock = 0; // Out of stock
    } else if (i % 10 === 0) {
      stock = (i % 8) + 1; // Low stock 1-8
    } else {
      stock = 25 + ((i * 23) % 420); // Normal stock
    }

    // Rating: 3.8 to 4.98
    const rating = Number((4.1 + ((i * 17) % 88) / 100).toFixed(2));
    const reviewCount = 8 + ((i * 31) % 480);

    // Build specs
    const specs: Record<string, string> = {};
    Object.entries(vocab.specsTemplates).forEach(([specKey, choices], idx) => {
      specs[specKey] = choices[(i + idx) % choices.length];
    });
    // Add dimensions & weight
    const weightGrams = 120 + ((i * 47) % 3400);
    specs['Weight'] = weightGrams > 1000 ? `${(weightGrams / 1000).toFixed(2)} kg` : `${weightGrams}g`;
    specs['Origin / Hub'] = vendor.location;

    // Tags
    const tags = [
      cat.name.split(' ')[0],
      subcategory.split(' ')[0],
      vocab.tagsPool[i % vocab.tagsPool.length],
      vocab.tagsPool[(i + 2) % vocab.tagsPool.length],
    ];

    // Images
    const primaryImg = vocab.images[i % vocab.images.length];
    const secondaryImg = vocab.images[(i + 1) % vocab.images.length];

    const id = `prod-${String(nextIdNum).padStart(3, '0')}`;
    nextIdNum++;

    const isFeatured = (i % 7 === 0);
    const isTrending = (i % 5 === 0);

    const product: Product = {
      id,
      name: productName,
      slug,
      headline: `${vocab.adjectives[i % vocab.adjectives.length]}. Engineered by ${vendor.name} in ${vendor.location}.`,
      description: `The ${productName} represents a quantum leap in ${cat.name.toLowerCase()} technology. Designed for discerning professionals and enthusiasts seeking uncompromising reliability, precision, and tactile satisfaction.\n\nHand-calibrated by master engineers at ${vendor.name}, every unit undergoes multi-stage cryptographic and environmental tolerance stress testing before deployment. Seamlessly connects with the UnifiedCommerce ecosystem for real-time telemetry and automated escrow logistics.\n\nBacked by our comprehensive 3-year multi-vendor lab warranty and 30-day holographic return protocol.`,
      price,
      originalPrice,
      currency: 'USD',
      category: cat.slug,
      subcategory,
      tags,
      vendorId: vendor.id,
      vendorName: vendor.name,
      vendorAvatar: vendor.logo,
      rating,
      reviewCount,
      stock,
      isFeatured,
      isTrending,
      badge: originalPrice ? 'DEAL' : isFeatured ? 'FEATURED' : undefined,
      images: [primaryImg, secondaryImg],
      specs,
      threedConfig: {
        geometry: (['polyhedron', 'torus', 'sphere', 'cylinder', 'crystal', 'drone'] as const)[i % 6],
        glowColor: cat.accentColor,
        metalness: 0.85,
        roughness: 0.15,
      },
      aiInsights: {
        demandScore: 65 + ((i * 13) % 34),
        sentimentSummary: `${Math.round(88 + ((i * 7) % 11))}% positive customer sentiment across verified telemetry reviews.`,
        frequentlyBoughtWith: [`prod-00${(i % 9) + 1}`, `prod-01${(i % 5) + 1}`],
      },
    };

    result.push(product);
  }

  return result;
}
